# Generated by Django 3.2.25 on 2024-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img_path', models.CharField(max_length=250)),
            ],
        ),
    ]
